#!/bin/bash

mkdir -p $(pwd)/robotframework

docker run -ti --rm \
  -e DISPLAY=$DISPLAY \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -v $(pwd)/robotframework:/var/robotframework_home/ \
  rijalati/robotframework-ride
